### ISSUE TITLE
Request for extra libflac-sys feature: build without OGG

### ISSUE THREAD

**Issue by dheijl** [nabijaczleweli/flac-bound#4]
Hi,

I've used flac-bound with great success in my little [swyh-rs](https://github.com/dheijl/swyh-rs) streaming app, but I did not want/need OGG support, so  I had to fork flac-bound to build libflac-sys without OGG support.
Hence my question: would it be possible to add a feature to build libflac-sys without OGG?

Thanks!

**Comment by nabijaczleweli** [comment]
Can you try the current `master` branch (at least 9cabdb02400145d6c6483a6651847644a34f5a96) and select the `libflac-noogg` feature instead of the `libflac` one?

**Comment by dheijl** [comment]
Thanks! I'll test tomorrow.

**Comment by dheijl** [comment]
I just tested it on Windows/MSVC and everything is OK.

Thanks for the quick response and the excellent interface for libflac-sys!

**Comment by nabijaczleweli** [comment]
Cool – released in [`v0.3.0`](https://github.com/nabijaczleweli/flac-bound/releases/tag/v0.3.0).
